import type { Metadata } from "next";
import "./globals.css"
import { Sidebar } from "lucide-react";

export const metadata: Metadata = {
  title: "Fundly",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {children}
        </body>
    </html>
  );
}
